### ISSUE TITLE
Users unable to update password under Profile section

### ISSUE THREAD

**Issue by obutov** [polonel/trudesk#187]
**Is this a BUG REPORT or FEATURE REQUEST?**:

- [x] BUG 
- [ ] FEATURE

**What happened**: Regular Users are unable to change the password through the Profile section. 

**What did you expect to happen**: Regular users should be able to set their own password.

**How to reproduce it (as minimally and precisely as possible)**: Login as a regular user. Navigate to the Profile page by clicking on User Icon > Profile, then update password fields. Click save. "Error undefined" is returned. 

**Anything else we need to know?**:

**Environment**:
- Trudesk Version: 1.0.9
- OS (e.g. from /etc/os-release): Windows 2008 R2
- Node.JS Version: 10.15.3 (x64)
- MongoDB Version: 4.0.6
- Is this hosted on cloud.trudesk.io: No

**Comment by obutov** [comment]
After further review, the API is returning "{"success":false,"error":"Not Authorized for this API call."}"
Though, I can't locate where that error is originating in the code.

**Comment by polonel** [comment]
fixed int `v1.0.11-beta`

**Comment by obutov** [comment]
This is still an issue in 1.0.11
When updating User profile, getting {"success":false,"error":"Not Authorized for this API call."}
