### ISSUE TITLE
Mail Checker Deletes Mail But Doesn't Create Ticket

### ISSUE THREAD

**Issue by DustyArmstrong** [polonel/trudesk#251]
**Is this a BUG REPORT or FEATURE REQUEST?**:

- [x] BUG 
- [ ] FEATURE

**What happened**:
Set up the mailer check, which does appear to access the mail address. I chose to "Delete Message" from the Inbox once processed, however it does not create a ticket. 

**What did you expect to happen**:
A ticket to be created within Trudesk. 

**How to reproduce it (as minimally and precisely as possible)**:
Set up the mailer check on port 993 for IMAP, applied settings. Check inbox of targeted account to note that email was deleted, check to note that no ticket is present. 

**Anything else we need to know?**:
My logs state "invalid log file...". 

I'm sorry to post two issues in one day. 

**Environment**:
- Trudesk Version: 1.0.12
- OS (e.g. from /etc/os-release): 18.04.2
- Node.JS Version: v10.16.0
- MongoDB Version: v3.6.13
- Is this hosted on cloud.trudesk.io: No

**Comment by DustyArmstrong** [comment]
Just to update, I tested on a fresh Ubuntu VM on a different host, in a different network, and had the same result. This was using the installation script, for reference. 

Everything else seems to work, and the mailer itself is working, just not the ticket creation.

**Comment by polonel** [comment]
What mail provider are you using?

**Comment by DustyArmstrong** [comment]
Tested with Gmail (IMAP), self hosted with provider (IMAP) and Exchange. 

Results are consistent, email inbox is opened, mail is deleted, but no ticket is created.

**Comment by polonel** [comment]
Thanks for the information. Looking into this issue

**Comment by cotanmarius** [comment]
Hello,

i could confirm this bug on my installation too.

**Environment:**

Trudesk Version: 1.0.15
OS (e.g. from /etc/os-release): Ubuntu 18.04.2 LTS x64
Node.JS Version: v10.16.1
MongoDB Version: v3.6.13
Is this hosted on cloud.trudesk.io: No

Email server is exchange server and we are using the port 993.
The symptoms are the same as  @DustyArmstrong described, the mails got deleted but no ticket is created.

**Comment by polonel** [comment]
Fix will be included in `v1.0.16`

**Comment by cotanmarius** [comment]
@polonel 
Thank you!

**Comment by cotanmarius** [comment]
@polonel 

I still have one question: i don't know exactly how this feature will work, but for example, if i have a ticket open and the support answers to my ticket, i shoud get an email. 

If i reply to this ticket over email, will trudesk recognize that it is a reply from me or will it create a new ticket for this answer?

Thank you!

**Comment by DustyArmstrong** [comment]
I tried merging from the develop branch into my local build, but still having the same problem. 

I'm going to assume that this is something I've done wrong, particularly since I have almost no experience with Github. I'll wait for the next release. 

Thanks for looking into it!

**Comment by polonel** [comment]
@cotanmarius No this is currently not possible. Right now email replies do not update the referenced ticket. This is something that hasn't made it into the Open Source version.

**Comment by dataedgehungary** [comment]
I merged from the dev branch update 7 days ago, still the same #254

**Comment by polonel** [comment]
did you do a `yarn build`?

Dev branch does not come with prebuilt files.

**Comment by dataedgehungary** [comment]
Well I only copied the edited mailercheck.js content, but then yes I ran a rebuild

**Comment by polonel** [comment]
Do you have the proper group added to your assigned department? There was also an update on the `develop` branch to allow setting "All Public Groups". This setting would allow all incoming tickets from incoming mail display in the ticket list view.  

Every error is caught with a `warn` log if it were to error out. Have you seen any `warn` messages?

If it works properly without the `autotls` option, my best guess is its an issue with the IMAP module.

**Comment by DustyArmstrong** [comment]
Updated (and completely re-installed) from the new release and results are still the same. Mail is checked, the email is deleted, but no ticket is created under any circumstance. 

Relevant customer from which the email is sent is registered on Trudesk, and assigned to a group. The log does not provide any information beyond `trudesk Ready` and subsequent `Invalid Log File`.

**Comment by polonel** [comment]
Updated to dev branch? Your about page shows 1.0.16-beta? Is your trudesk account a member of a team/department that has access to *All Groups* or the group the user is a member of? Do you have permissions to "Manage Public Tickets" in `Settings->Permission`

I manually tested with, Yahoo, Gmail, Outlook.com, Office 365, Exchange, ProtonMail, Zoho before I pushed to dev.

Please verify.

**Comment by cotanmarius** [comment]
@polonel 
is this update still in beta?

**Comment by polonel** [comment]
Its being pushed to `1.0.16` this weekend.

**Comment by haakonnessjoen** [comment]
I am having this issue still with v1.0.16. With logging set to on, it says: `Processed 2 Mail > Ticket`, but nothing more about creating any tickets or anything else. And nothing happens in the web interface.

**Comment by dataedgehungary** [comment]
We still had the issue with the new version too. We think that async processes cause the problem, the email gets deleted before it can be imported.

We manged to temporarily "cure the symptoms" by adding a Timeout:

`function bindImapReady () {
  try {
    mailCheck.Imap.on('end', function () {
        setTimeout(function () {
        handleMessages(mailCheck.messages)
        mailCheck.Imap.destroy()
        }, 1000)
    })
...
`

**Comment by cotanmarius** [comment]
Any update?

**Comment by polonel** [comment]
Should be fixed in `v1.1.2`

**Comment by teutat3s** [comment]
It looks like this is still an issue with a fresh install of version `1.1.3` running on docker. Please take a look at the following debug log:

```
7/8 11:23:02 [85497] - ^[[34mdebug^[[39m: Processing 1 Mail --> src/mailer/mailCheck.js#L152
7/8 11:23:02 [85497] - ^[[34mdebug^[[39m: DEBUG Imap.end() called  --> src/mailer/mailCheck.js#L220
7/8 11:23:02 [85497] - ^[[34mdebug^[[39m: DEBUG message pushed:  from=me@example.com, subject=[test] Help me please, body=<p>This is a test issue send via mail.</p><p>Big bug, big problem, please fix.</p>  --> src/mailer/mailCheck.js#L194
```

It seems like the `Imap.end()` call comes a bit too early, right? It should then continue to `winston.debug('Created %s tickets from mail', count)`, but it doesn't.
No ticket gets created, but the message gets deleted / read. If I can be of help to debug this further, please tell me.
