### ISSUE TITLE
Mail Checker Bug: Mail will be deleted without creating a ticket

### ISSUE THREAD

**Issue by cotanmarius** [polonel/trudesk#299]
**Is this a BUG REPORT or FEATURE REQUEST?**:

- [ x] BUG 
- [ ] FEATURE

**What happened**:
Set up the mailer check, which does appear to access the mail address. I chose to "Delete Message" from the Inbox once processed, however it does not create a ticket.

The user with the email address from which i am sending the email does exist on trudesk.

I have also tried with other email addresses which does not have an user assigned on trudesk, but still the same problem. No ticket or user is getting created.

What did you expect to happen:
A ticket to be created within Trudesk.

How to reproduce it (as minimally and precisely as possible):
Set up the mailer check on port 993 for IMAP, applied settings. Check inbox of targeted account to note that email was deleted, check to note that no ticket is present.

**What did you expect to happen**:
A ticket to be created within Trudesk.

**How to reproduce it (as minimally and precisely as possible)**:
I am using Microsoft Exchange 2016, sending an email at helpdesk@something.com , i can see the email in the inbox, i will not touch anything or read the email.

After one minute, the email will be deleted from my inbox.

**Anything else we need to know?**:
Related to this bug: 
https://github.com/polonel/trudesk/issues/251

**Environment**:
Trudesk Version: 1.1.1
OS (e.g. from /etc/os-release): 18.04.2
Node.JS Version: v10.18.0
MongoDB Version: v3.6.13
Is this hosted on cloud.trudesk.io: No

**Comment by polonel** [comment]
Should be fixed in `v1.1.2`

**Comment by cotanmarius** [comment]
Hello,

@polonel : Thank you for the update.
I have installed the last version but, unfortunatelly, it is still not working :(
I cannot find anything in logs, it seemst nothing is loged expecting the startup of nodejs.

I have tried to reset the setting to default and delete every departments and user groups i have created and also assured that "All Groups" and "All Public Groups" are checked on the default department.

Is there something i can do/check?

Thank you!

**Comment by polonel** [comment]
I tested with multiple IMAP providers including Exchange after making these changes. I tested with a fresh ubuntu install from the ubuntu install script and all went well. I suggest giving it a try with a fresh install if you can.
